spring:
  application:
    # name will show up in eureka interface
    #same name as .yml in config server
    name: schools
  # config to config server
  config:
    import: optional:configserver:http://localhost:8888