spring:
  application:
    name: students # name will show up in eureka interface
  # config to config server
  config:
    import: optional:configserver:http://localhost:8888

  # ==> run student services will be registered in discovery services
