#tell eureka to read config from config server
spring:
  application:
    name: discovery
  config:
    import: optional:configserver:http://localhost:8888
    #optional = if this micro service doesnt find the config in config server
    # it will not fail to start up
    # 8888 port wil be given to config server
